//
// Created by Eliud Garcia on 2/24/26.
//

#ifndef CS460_PROJECT_1_AVAILABILITYCONTROLLER_H
#define CS460_PROJECT_1_AVAILABILITYCONTROLLER_H


class AvailabilityController {
};


#endif //CS460_PROJECT_1_AVAILABILITYCONTROLLER_H