//
// Created by Eliud Garcia on 2/24/26.
//

#ifndef CS460_PROJECT_1_PARKINGSPOTCONTROLLER_H
#define CS460_PROJECT_1_PARKINGSPOTCONTROLLER_H


class ParkingSpotController {
};


#endif //CS460_PROJECT_1_PARKINGSPOTCONTROLLER_H